### ISSUE TITLE
Some example issue

### ISSUE THREAD

**Issue by Jordomav** [Level-Hero/social-media#11]
This is some functionality that needs to be done so that I can allow users to add new friends

**Comment by Jordomav** [comment]
I attempted to fix this but with no success

**Comment by VanTaro** [comment]
It doesn't look like anything to me.

**Comment by Jordomav** [comment]
@jordomav I still cant get this can you help

**Comment by Mrzebrasmoothie** [comment]
Probably not
:P

**Comment by VanTaro** [comment]
@Jordomav @Mrzebrasmoothie @GreenJoker96 Hey, I've fallen, and I can't get up!.

**Comment by Mrzebrasmoothie** [comment]
Call code alert

**Comment by Jordomav** [comment]
I finished this functionality by doing this thing
