### ISSUE TITLE
Email Confirmation 

### ISSUE THREAD

**Issue by Jordomav** [Level-Hero/social-media#5]
We should make sure that the email someone is attempting to use is the correct email. To do this I would look into the NPM package `mailgun`. This also means we would need a route that would validate the user. For example, on the User schema I would have a Boolean(True/False) called `isValidated` and be default set it to `false`. The send the email to the user with a link that goes to an API route that changes that Boolean to true. Only then should we let the user edit their profile and do any App changing functionalities.

**Comment by VanTaro** [comment]
Merged #34
